services:
  django:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - ASSETS_URL=${ASSETS_URL}
			
    volumes:
      - .:/home/my-user/app
      - external-storage:/media/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shared_network

volumes:
  external-storage:
    external: true

networks:
  shared_network:
    external: true
