# Generated by Django 5.1.1 on 2024-11-09 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleCourse', models.CharField(max_length=255, verbose_name='Título do curso')),
                ('description', models.TextField(verbose_name='Descrição do curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Curso')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school_contebras_core_course.course')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do aluno')),
                ('studentEmail', models.EmailField(max_length=100, verbose_name='Email do aluno')),
                ('classroom', models.ManyToManyField(related_name='student', to='school_contebras_core_course.classroom', verbose_name='Turma')),
                ('course', models.ManyToManyField(related_name='student', to='school_contebras_core_course.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='RegistrationClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Matriculado em')),
                ('last_monthly_date', models.DateField(blank=True, null=True, verbose_name='Data da ultima mensadidade')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.classroom', verbose_name='matriculado na turma')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_contebras_core_course.student', verbose_name='nome do aluno')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
    ]
